---
abstract: 'Apply PodWeaver if there is already Pod'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PodWeaverIfPod
requires:
  Dist::Zilla::Plugin::PodWeaver: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-PodWeaverIfPod
  repository: git://github.com/jonswar/perl-dzil-podweaverifpod.git
version: 0.02
